version: '3.8'

name: geographic-information-systems
services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    env_file: ./database/.env
    healthcheck:
      test: "pg_isready --dbname=geographic-information-systems --host=localhost --username=student && psql --dbname=geographic-information-systems --username=student --list"
      timeout: 5s
      retries: 20
    ports:
      - "5432:5432"
    volumes:
      - ./database/data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      database:
        condition: service_healthy
    env_file: ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
