version: '3.8'

name: geographic-information-systems-lecture
services:
  database:
    build:
      context: ./database
    env_file: ./database/.env
    ports:
      - "5432:5432"
    volumes:
      - ./database/data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    depends_on:
      - database
    env_file: ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
