name: geographic-information-systems-lecture
services:
  database:
    build:
      context: ./database
    env_file: ./database/.env
    ports:
      - "6543:5432"
    volumes:
      - ./database/data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    depends_on:
      - database
    env_file: ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    networks:
      - default

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - default
      
networks:
  default:
    name: gis-network
